name: github-pages

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install dependencies
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - run: npm ci

      # Creates the production build in "dist" folder
      - run: npm run build

      # Upload dist folder with a specific name so that deploy-pages action recognizes it.
      - uses: actions/upload-pages-artifact@v1
        with:
          name: github-pages
          path: dist
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages # unclear if this value needs to be exact
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: github-pages

      # More information at https://github.com/actions/deploy-pages
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.2.3
